### ISSUE TITLE
Create new documentation

### ISSUE THREAD

**Issue by jpmckinney** [opennorth/represent-canada#99]
### [Tasks: Request boundaries](https://github.com/opennorth/represent-canada/wiki/Tasks%3A-Request-boundaries)

* [x] Requesting boundaries (similar sections to Represent CSV Schema docs)
* [x] Adding a boundary: `define` task, run all tasks with `--base`, run `spreadsheet` as normal
* [x] Handling slug collisions, like 'Richmond, NS' and 'Paroisse de Plessisville'
* [x] Making an MFIPPA request (sample text, upload past requests)
* [x] Refer to [Google Sheets Mail Merge](https://developers.google.com/apps-script/articles/mail_merge)

### [Tasks: Respond to emails](https://github.com/opennorth/represent-canada/wiki/Tasks%3A-Respond-to-emails)

* [x] Requests for new data (ask budget)
* [x] Offers to supply data (spreadsheet option)
* [x] Postal code errors (boilerplate response)
* [x] Outdated/missing data (fix scrapers-ca)
* [x] Creating app (ask for link when ready)
* [x] Updating the users spreadsheets

**Comment by jpmckinney** [comment]
# Adding the logo / translation to http://represent.opennorth.ca/government/

In your browser:

* Search `[municipality] logo` on [Google Images](https://images.google.com/). If different municipalities have the same name, you may need to add the province.
* Click 'Tools' and select 'Black and white' from 'Color' to see if there are any official black-and-white versions of the logo
* Download a high resolution version of the logo, preferably in PNG format

In an image editor:

* Change the image to grayscale
* Trim the borders
* Resize the image height to 100 pixels
* If the width is an odd number, increase the canvas width by 1 pixel 
* Save the image as PNG-24 with a filename like `[municipality].png` to `finder/static/img/logos/`

In a text editor:

* Edit `finder/templates/government.html` and add a new `img` tag to the end
* `cd finder && python ../manage.py makemessages -l fr && cd ..`
* `./manage.py makemessages -l fr`
* `git diff` to see what new translations were added
* Edit the new translations in `finder/locale/fr/LC_MESSAGES/django.po`
  * Change the `msgstr` and remove the lines like:

```
#, fuzzy
#| msgid "City of Municipality"
```

* `cd finder && python ../manage.py compilemessages && cd ..`
* `./manage.py compilemessages`

Troubleshooting:

`OSError: dlopen(/usr/local/lib/libgdal.dylib, 6): Symbol not found: _GEOSArea`

```
GDAL_LIBRARY_PATH = '/usr/local/lib/libgdal.dylib'
import ctypes
ctypes.CDLL(GDAL_LIBRARY_PATH)
```

`CommandError: Can't find msguniq. Make sure you have GNU gettext tools 0.15 or newer installed.`

```
brew info gettext
cd /usr/local/Cellar/gettext/VERSION/bin
ln -ns msgattrib msgfmt msgmerge msguniq xgettext /usr/local/bin
```

**Comment by jpmckinney** [comment]
Deployment

* [x] Access to servers
* [x] Server configuration
* [x] AWS failover configuration
* [x] Fabric commands
* [x] Heroku apps
* [x] Cloudfront and image-proxy
